A cute little demo showing the simplest usage of minGPT. Configured to run fine on Macbook Air in like a minute.

In [1]:
import torch
from torch.utils.data import Dataset
from torch.utils.data.dataloader import DataLoader
from mingpt.utils import set_seed
import numpy as np
set_seed(3407)

In [2]:
# process dataset
from mingpt.bpe import Encoder, get_encoder
e = get_encoder()
# x_gpt = [e.encode(d) for d in x.split()]
# y_gpt = e.encode_equation(y)
# calcu = eval(y)

In [1]:
raw_data_path = '24/answer.txt'
with open(raw_data_path, 'r') as f:
    raw_data = f.readlines()

raw_set = list()
for item in raw_data:
    x, y = item.strip().split(':')
    x, y = x.strip(), y.strip()
    if 'nope' in y:
        y = 'no answer'
    else:
        y = y.replace('×', '*')
    raw_set.append((x, y))

raw_set[515:525]

[('2 2 8 11', 'no answer'),
 ('2 2 8 12', '12+2+2+8'),
 ('2 2 8 13', 'no answer'),
 ('2 2 9 9', 'no answer'),
 ('2 2 9 10', '(9-2)*2+10'),
 ('2 2 9 11', '11+2+2+9'),
 ('2 2 9 12', '(2+2)*9-12'),
 ('2 2 9 13', 'no answer'),
 ('2 2 10 10', '10+10+2+2'),
 ('2 2 10 11', '(11*2-10)*2')]

In [4]:
# some stats
cnt_1_9 = cnt_1_9yes = cnt_1_9_no = 0
for x, y in raw_set:
    digits = x.split()
    if all(int(d) < 10 for d in digits):  # 只看 1 到 9
        cnt_1_9 += 1
        if 'no' in y:
            cnt_1_9_no += 1
        else:
            cnt_1_9yes += 1
print(cnt_1_9, cnt_1_9yes, cnt_1_9_no)

495 404 91


In [18]:
# split train/test
import numpy as np
set1_9 = [(x, y) for x, y in raw_set if all(int(d) < 10 for d in x.split()) and 'no' not in y]
# print(set1_9[:10])
np.random.seed(0)
np.random.shuffle(set1_9)
train_xys, test_xys = set1_9[:-80], set1_9[-80:]
# print(len(train_xys), len(test_xys))
# print(train_xys[:10])
print(test_xys[:10])

[('2 2 2 4', '(2+2+2)*4'), ('4 7 8 9', '(7+8-9)*4'), ('6 8 9 9', '(9+9)*8/6'), ('3 3 8 9', '(3+8)*3-9'), ('4 4 5 7', '(4+7-5)*4'), ('2 4 6 9', '(4-2)*9+6'), ('1 3 9 9', '(9-1)*9/3'), ('1 6 8 8', '(1+8-6)*8'), ('4 6 6 7', '(7-4)*6+6'), ('5 5 6 7', '(5*5+6)-7')]


In [15]:
import pickle
with open('24/dataset1_9.pkl', 'wb') as f:
    res = {'train': train_xys, 'test': test_xys}
    pickle.dump(res, f)

In [17]:
with open('24/dataset1_9.pkl', 'rb') as f:
    res = pickle.load(f)
print(list(res.keys()))

['train', 'test']


In [4]:
class FixedLenDataset(Dataset):
    """
    Dataset for the Sort problem. E.g. for problem length 6:
    Input: 0 0 2 1 0 1 -> Output: 0 0 0 1 1 2
    Which will feed into the transformer concatenated as:
    input:  0 0 2 1 0 1 0 0 0 1 1
    output: I I I I I 0 0 0 1 1 2
    where I is "ignore", as the transformer is reading the input sequence
    """

    def __init__(self, raw_set):
        self.raw_set = raw_set
        self.tokenizer = get_encoder()
        self.max_len = 14  # 统计最大14

    def __len__(self):
        return len(self.raw_set)

    def get_vocab_size(self):
        return 50257

    def get_block_size(self):
        # fixed length version:
        # return self.length * 2 - 1
        # return 4 + 4 + 3 + 2 - 1  # 4数字+4数字+3运算符+2括号-1 = 12

        # padding version:
        return self.max_len

    def __getitem__(self, idx):
        inp, sol = self.raw_set[idx]
        inpp = [self.tokenizer.encode(d)[0] for d in inp.split()]
        soll = self.tokenizer.encode(sol) if 'no answer' in sol else self.tokenizer.encode_equation(sol)
        # padding here
        padding_len = self.max_len - len(inpp) - len(soll) + 1
        soll += [50256] * padding_len

        # print(inpp, soll)
        inpp, soll = torch.tensor(inpp, dtype=torch.long), torch.tensor(soll, dtype=torch.long)

        # concatenate the problem specification and the solution
        cat = torch.cat((inpp, soll), dim=0)

        # the inputs to the transformer will be the offset sequence
        x = cat[:-1].clone()
        y = cat[1:].clone()
        # we only want to predict at output locations, mask out the loss at the input locations
        y[:3] = -1  # 固定4数字
        y[-padding_len + 1:] = -1
        return x, y

In [5]:
ixes = list(range(len(raw_set)))
np.random.shuffle(ixes)
train_ixes = ixes[:-200]
test_ixes = ixes[-200:]
train_set = [raw_set[i] for i in train_ixes]
test_set = [raw_set[i] for i in test_ixes]
train_dataset = FixedLenDataset(train_set)
test_dataset = FixedLenDataset(test_set)

In [29]:
x, y = train_dataset[400]
print(len(x))
for a, b in zip(x,y):
    print(int(a),int(b))

14
22 -1
22 -1
22 -1
1065 7
7 22
22 10
10 22
22 8
8 9
9 1065
1065 14
14 22
22 50256
50256 -1


In [7]:
max_len = 0
for x, y in train_dataset:
    max_len = max(max_len, len(x))
print(max_len)

14


In [8]:
# create a GPT instance
from mingpt.model import GPT

model_config = GPT.get_default_config()
model_config.model_type = 'gpt-nano'
model_config.vocab_size = train_dataset.get_vocab_size()
model_config.block_size = train_dataset.get_block_size()
model = GPT(model_config)

number of parameters: 2.50M


In [9]:
# create a Trainer object
from mingpt.trainer import Trainer

train_config = Trainer.get_default_config()
train_config.learning_rate = 5e-4 # the model we're using is so small that we can go a bit faster
train_config.max_iters = 10000
train_config.batch_size = 64
train_config.num_workers = 0
trainer = Trainer(train_config, model, train_dataset)

running on device cpu


In [10]:
def eval_split(dataset):
    model.eval()
    losses = list()
    loader = DataLoader(dataset, batch_size=10, num_workers=0, drop_last=False)
    for batch in loader:
        batch = [t.to(trainer.device) for t in batch]
        x, y = batch
        # forward the model
        with torch.no_grad():
            logits, loss = model(x, y)
        losses.append(loss)

    model.train()
    return np.mean(losses)

In [11]:
def batch_end_callback(trainer):
    if trainer.iter_num % 200== 0:
        print(f"iter_dt {trainer.iter_dt * 1000:.2f}ms; iter {trainer.iter_num}: train loss {trainer.loss.item():.5f}")
        test_loss = eval_split(test_dataset)
        print(f"    test loss {test_loss:.5f}")
trainer.set_callback('on_batch_end', batch_end_callback)

trainer.run()

iter_dt 0.00ms; iter 0: train loss 10.82069
    test loss 10.68197
iter_dt 185.18ms; iter 200: train loss 2.46511
    test loss 2.43127
iter_dt 176.05ms; iter 400: train loss 1.10322
    test loss 1.03616
iter_dt 179.25ms; iter 600: train loss 0.81373
    test loss 0.75862
iter_dt 171.47ms; iter 800: train loss 0.73295
    test loss 0.67568
iter_dt 165.59ms; iter 1000: train loss 0.67413
    test loss 0.63003
iter_dt 169.07ms; iter 1200: train loss 0.66450
    test loss 0.60337
iter_dt 172.33ms; iter 1400: train loss 0.64342
    test loss 0.57751
iter_dt 171.17ms; iter 1600: train loss 0.64861
    test loss 0.57636
iter_dt 176.42ms; iter 1800: train loss 0.66497
    test loss 0.56110
iter_dt 175.14ms; iter 2000: train loss 0.51268
    test loss 0.53968
iter_dt 172.73ms; iter 2200: train loss 0.53884
    test loss 0.54911
iter_dt 176.10ms; iter 2400: train loss 0.54317
    test loss 0.52718
iter_dt 172.55ms; iter 2600: train loss 0.48477
    test loss 0.54084
iter_dt 170.54ms; iter 2800

KeyboardInterrupt: 

In [12]:
##################### until now #####################

In [36]:
def generate_1by1(model):
    # 先batch生成，再每个遍历直到第一个终止符
    loader = DataLoader(test_dataset, batch_size=1, num_workers=0, drop_last=False)
    model.eval()
    for i, batch in enumerate(loader):
        batch = [t.to(trainer.device) for t in batch]
        x, y = batch
        # forward the model
        inp = x[:, :4]
        out = model.generate(inp, 10, do_sample=False)
        if 15 <= i < 25:
            print(inp, out)
            print(test_dataset.tokenizer.decode(out[0][4:].cpu().squeeze().tolist()))
        if i >= 25:
            break

generate_1by1(model)

tensor([[19, 20, 24, 24]]) tensor([[   19,    20,    24,    24,     7,    19,     9,    24,    12,    20,
             8,    12,    24, 50256]])
(4*9-5)-9<|endoftext|>
tensor([[  16,   18,  940, 1485]]) tensor([[   16,    18,   940,  1485,     7,    16,     9,   940,    10,  1485,
             8,    10,    18, 50256]])
(1*10+13)+3<|endoftext|>
tensor([[  19,   20,   21, 1485]]) tensor([[   19,    20,    21,  1485,     7,  1485,    12,    21,     8,     9,
            19,    12,    20, 50256]])
(13-6)*4-5<|endoftext|>
tensor([[21, 21, 21, 23]]) tensor([[   21,    21,    21,    23,    21,     9,    23,    14,     7,    21,
            10,    21,     8, 50256]])
6*8/(6+6)<|endoftext|>
tensor([[  19,   23, 1157, 1485]]) tensor([[   19,    23,  1157,  1485,     7,  1485,    12,    23,     8,     9,
          1157,    12,    19, 50256]])
(13-8)*11-4<|endoftext|>
tensor([[  17,   23,   24, 1485]]) tensor([[   17,    23,    24,  1485,     7,  1485,    10,    23,    14,    17,
             8,  

In [13]:
exit()
# now let's perform some evaluation
model.eval()

GPT(
  (transformer): ModuleDict(
    (wte): Embedding(50257, 48)
    (wpe): Embedding(14, 48)
    (drop): Dropout(p=0.1, inplace=False)
    (h): ModuleList(
      (0): Block(
        (ln_1): LayerNorm((48,), eps=1e-05, elementwise_affine=True)
        (attn): CausalSelfAttention(
          (c_attn): Linear(in_features=48, out_features=144, bias=True)
          (c_proj): Linear(in_features=48, out_features=48, bias=True)
          (attn_dropout): Dropout(p=0.1, inplace=False)
          (resid_dropout): Dropout(p=0.1, inplace=False)
        )
        (ln_2): LayerNorm((48,), eps=1e-05, elementwise_affine=True)
        (mlp): ModuleDict(
          (c_fc): Linear(in_features=48, out_features=192, bias=True)
          (c_proj): Linear(in_features=192, out_features=48, bias=True)
          (act): NewGELU()
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
      (1): Block(
        (ln_1): LayerNorm((48,), eps=1e-05, elementwise_affine=True)
        (attn): CausalSelfAtten

In [14]:
def eval_split(trainer, split, max_batches):
    dataset = {'train':train_dataset, 'test':test_dataset}[split]
    results = []
    mistakes_printed_already = 0
    loader = DataLoader(dataset, batch_size=100, num_workers=0, drop_last=False)
    for b, (x, y) in enumerate(loader):
        x = x.to(trainer.device)
        y = y.to(trainer.device)
        # isolate the input pattern alone
        inp = x[:, :4]
        sol = y[:, 4:]
        # let the model sample the rest of the sequence
        cat = model.generate(inp, 14 - 4, do_sample=False) # using greedy argmax, not sampling
        sol_candidate = cat[:, n:] # isolate the filled in sequence
        # compare the predicted sequence to the true sequence
        correct = (sol == sol_candidate).all(1).cpu() # Software 1.0 vs. Software 2.0 fight RIGHT on this line haha
        for i in range(x.size(0)):
            results.append(int(correct[i]))
            if not correct[i] and mistakes_printed_already < 3: # only print up to 5 mistakes to get a sense
                mistakes_printed_already += 1
                print("GPT claims that %s sorted is %s but gt is %s" % (inp[i].tolist(), sol_candidate[i].tolist(), sol[i].tolist()))
        if max_batches is not None and b+1 >= max_batches:
            break
    rt = torch.tensor(results, dtype=torch.float)
    print("%s final score: %d/%d = %.2f%% correct" % (split, rt.sum(), len(results), 100*rt.mean()))
    return rt.sum()

# run a lot of examples from both train and test through the model and verify the output correctness
with torch.no_grad():
    train_score = eval_split(trainer, 'train', max_batches=50)
    test_score  = eval_split(trainer, 'test',  max_batches=50)

NameError: name 'n' is not defined

In [ ]:
# let's run a random given sequence through the model as well
n = train_dataset.length # naugy direct access shrug
inp = torch.tensor([[0, 0, 2, 1, 0, 1]], dtype=torch.long).to(trainer.device)
assert inp[0].nelement() == n
with torch.no_grad():
    cat = model.generate(inp, n, do_sample=False)
sol = torch.sort(inp[0])[0]
sol_candidate = cat[:, n:]
print('input sequence  :', inp.tolist())
print('predicted sorted:', sol_candidate.tolist())
print('gt sort         :', sol.tolist())
print('matches         :', bool((sol == sol_candidate).all()))